version: "3"

services:
  tomcat1:
    build:
      context: ./TomcatServer
      dockerfile: Dockerfile
    container_name: tomcat1
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=mysql
      - DB_ROOT=root
      - DB_PASS=root
      - DB_PORT=3306
      - DB_NAME=DSMTDB
      - JWT_SECRET=KsKwl201A8x9K77
    ports:
      - 8080:8080
    volumes:
      - ./TomcatServer:/workspace

  tomcat2:
    build:
      context: ./TomcatServer
      dockerfile: Dockerfile
    container_name: tomcat2
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=mysql
      - DB_ROOT=root
      - DB_PASS=root
      - DB_PORT=3306
      - DB_NAME=DSMTDB
      - JWT_SECRET=KsKwl201A8x9K77
    ports:
      - 8084:8080
    volumes:
      - ./TomcatServer:/workspace

  balancer:
    image: nginx:latest
    container_name: balancer
    stdin_open: true
    tty: true
    ports:
      - 80:80
    depends_on:
      - tomcat1
      - tomcat2
    volumes:
      - .\Nginx\nginx.conf:/etc/nginx/nginx.conf:ro

  chat_server:
    build:
      context: ./ChatServer
      dockerfile: Dockerfile
    container_name: erlang_chat
    ports:
      - 8081:8080
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./ChatServer:/workspace

  notification_server:
    build:
      context: ./NotificationServer
      dockerfile: Dockerfile
    container_name: erlang_notification
    ports:
      - 8083:8080
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./NotificationServer:/workspace

  mysql:
    image: mysql:latest
    container_name: database
    ports:
      - 8082:3306
    stdin_open: true
    tty: true
    environment:
      - TZ="Europe/Rome"
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./Database/data:/var/lib/mysql
      - ./Database/scripts:/scripts
